name: MacOS (Static Library)
on: 
  push:
    paths:
      - '*.txt'
      - 'example/**'
      - 'lib_source/**'
      - 'scripts/**'
      - '.github/workflows/macos-static.yml'
  pull_request:
    paths:
      - '*.txt'
      - 'example/**'
      - 'lib_source/**'
      - 'scripts/**'
      - '.github/workflows/macos-static.yml' 
      
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        qt_ver: [6.6.3]
        qt_arch: [clang_64]
    env:
      targetName: RibbonUI-APP
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          modules: 'qt5compat qtmultimedia qtshadertools qtimageformats'
          
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
        with:
          version: 1.10.2
          
      - name: build macos
        run: |
          cmake --version
          mkdir build
          cd build
          cmake -DCMAKE_MESSAGE_LOG_LEVEL=STATUS -DCMAKE_PREFIX_PATH=/Users/runner/work/RibbonUI/Qt/${{ matrix.qt_ver }}/macos -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DRIBBONUI_BUILD_STATIC_LIB=ON -GNinja ..
          cmake --build . --target all --config Release --parallel
          
      - name: package
        run: |
          # 先删除所有dSYM文件，减少包的体积
          sudo find /Users/runner/work/RibbonUI/Qt/${{ matrix.qt_ver }}/macos/qml -name "*.dSYM" | xargs rm -r
          # 拷贝依赖
          sudo macdeployqt /Users/runner/work/RibbonUI/RibbonUI/build/app/release/${targetName}.app -qmldir=. -verbose=1 -dmg     
          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.targetName }}_${{ matrix.os }}_${{matrix.qt_ver}}_static.zip
          path: /Users/runner/work/RibbonUI/RibbonUI/build/app/release/${{ env.targetName }}.dmg
          
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /Users/runner/work/RibbonUI/RibbonUI/build/app/release/${{ env.targetName }}.dmg
          asset_name: ${{ env.targetName }}_${{  github.ref_name }}_${{ matrix.os }}_Qt${{ matrix.qt_ver }}_static.dmg
          tag: ${{ github.ref }}
          overwrite: true
